### PR TITLE
Use raw pinning to prevent mismatches in `buttons[pin]`.

### PR DESCRIPTION
**Pull request by vicary**
Otherwise no events will actually emit.

### CODE REVIEW

**Comment by bnielsen1965** [comment]
Should the gpio.setMode() come before the pins.forEach ... buttonSetup(pin)?

**Comment by bnielsen1965** [comment]
I did some testing and the gpio.setMode() call can come before or after the buttonSetup() call.

However, if you try to use MODE_BCM in the current rpi-gpio-buttons it will fail.

The current rpi-gpio dependency of 0.8.1 has a bug which results in pin export failures when using MODE_BCM.

Before allowing MODE_BCM there are multiple changes needed...

- The  package.json dependency for rpi-gpio needs to be changed. I tested 0.9.1 and it works.
- The mode should be an option in rpi-gpio-buttons when configuring so the user can select the mode. I.E. var buttons = require('rpi-gpio-buttons')([17, 27], { mode: gpio.MODE_BCM });
- The documentation needs to be updated to inform the use of the different pin options, RPI vs BCM.

**Comment by bnielsen1965** [comment]
I just published version 1.1.0 which adds a mode option when creating an instance of rpi-gpio-buttons. The default mode is still MODE_RPI to prevent breaking current applications, but you can now specify MODE_BCM to enable the use of the BCM GPIO numbers. I.E.

var rpi_gpio_buttons = require('rpi-gpio-buttons');
var buttons = rpi_gpio_buttons([17, 27], { mode: rpi_gpio_buttons.MODE_BCM });

**Comment by vicary** [comment]
Sorry I was struggling for time to make this in my fork, thank you so much!

**Comment by bnielsen1965** [comment]
No problem, I assumed you had your hands full.

**Pull request closed without merging**
